honeycombio/otel-config-go

launcher/launcher.go
launcher/launcher_test.go

When we set the debug log level we attempt to marshal the config as JSON over [here](https://github.com/honeycombio/opentelemetry-go-contrib/blob/launcher/launcher/config.go#L563)
This fails if you have provided a `Logger` or `ShutdownFunctions` so we should omit from the JSON
Add JSON tags to the config struct to omit the fields we cannot serialise
run the tests

fix: Omit config fields we cannot serialise

---

launcher/launcher.go
launcher/launcher_test.go

Currently passing `launcher.WithSampler(myCustomSampler)` into  `launcher.ConfigureOpenTelemetry` & friends doesn't do anything.
This PR ensures that when constructing the `pipelines.PipelineConfig` it passes in the provided `launcher.Config.Sampler` instead of not.
Added a test using the `dummyGRPCServer` & an extended `testSampler` that shows that the sampler isn't being used. Then updated the `pipelines.NewTracePipeline(pipelines.PipelineConfig{...})` to include the passed in `Sampler` and watched the test start passing.

fix: `launcher.WithSampler` doesn't get passed all the way through

---

.github/dependabot.yml

- no dependabot
- Create .github/dependabot.yml
dependabot PRs start coming through when newer versions of dependencies are available

maint: add dependabot to project

---

.circleci/config.yml

Go 1.20 was released in February!
Add 1.20 to test matrix and use as default version.
Tests still pass

ci: add go 1.20 to ci

---

launcher/launcher.go
launcher/launcher_test.go

Allows vendors to set the default exporter endpoint instead of having to rely on using a vendor option as using a vendor option always squashes the `OTEL_EXPORTER_OTLP_ENDPOINT` env var.
Setting the default before creating the options struct allows it to fallback as expected: eg option > env var > default
Add new DefaultExporterEndpoint variable for vendors to set during their package init.
Added unit tests to verify behaviour, both in setting it and checking the fallback behaviour.

feat: Allow vendors to set default exporter endpoint

---

otelconfig/otelconfig.go
otelconfig/otelconfig_test.go

Calling this code:
```go
otelshutdown, err := otelconfig.ConfigureOpenTelemetry(
otelconfig.WithExporterProtocol(otelconfig.ProtocolHTTPJSON)))
```
Crashes with a fatal error, even though the function returns an error.
It would be nice to be able to catch this error and handle it in my app appropriately.
Return a wrapped error instead of crashing. Note that this also affects other setup-type errors that are currently fatally crashing, and required reworking some tests.
Run the tests, or the code above; `err` should come back as non-nil and it shouldn't crash.

fix: Don't fatal error when we can return an error

---

otelconfig/otelconfig.go
otelconfig/otelconfig_test.go

We are unable to add resource detectors when configuring the launcher.
- Closes #12
Rather than adding a specific `WithDetectors` func to mirror the functionality in the [resource package](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/resource#WithDetectors) this adds a more generic version so that any resource option configuration can be provided.
This has been done in a backwards compatible manner but I could see a future where the `WithResourceAttributes` function is removed as it is duplicate functionality now.
Unit tests have been added

feat: Add resource option configuration

---

otelconfig/otelconfig.go
otelconfig/otelconfig_test.go

This implementation of adding resource attributes with code clobbers resource attributes set from environment variables which is against spec.
This reverts commit 6365f2db2824c5a112dfdad5f9a215a0b83790ff.

fix: revert "feat: Add resource option configuration (#47)"

---

examples/main.go
otelconfig/otelconfig.go
otelconfig/otelconfig_test.go
smoke-tests/docker-compose.yml
smoke-tests/smoke-sdk-grpc.bats
smoke-tests/smoke-sdk-http.bats

We are unable to add resource detectors when configuring the launcher.
- Closes #12
Implementation starts with what was written for #47 with smoke tests added to verify the order of precedence for resources attributes from environment over code.
[vera] upon further inspection, the original behavior of CODE attributes winning over ENV attributes was valid:
> The SDK MUST extract information from the OTEL_RESOURCE_ATTRIBUTES environment variable and [merge](https://opentelemetry.io/docs/specs/otel/resource/sdk/#merge) this, as the secondary resource, with any resource information provided by the user, i.e. the user provided resource information has higher priority.
— [OTel Resource SDK spec](https://opentelemetry.io/docs/specs/otel/resource/sdk/#specifying-resource-information-via-an-environ …

feat: Add WithResourceOption for additional resource configuration

---

otelconfig/otelconfig.go
otelconfig/otelconfig_test.go

When using detectors with mis-matched Schema URLs, resource.New will return an error. Previously, this was dropped and consequently it looked like configuration worked but many resource attributes would be missing in the resulting telemetry.
With the recent addition of https://github.com/honeycombio/otel-config-go/pull/48, this error is much easier to hit. For example, the detectors built into opentelemetry-go [import](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/resource/builtin.go#L25) semconv `v1.17.0` but this project [pulls in](https://github.com/honeycombio/otel-config-go/blob/main/otelconfig/otelconfig.go#L21) `v1.18.0`. This means that adding something like `otelconfig.WithResourceOption(resource.WithHost())` results in a mis-configured OTel and no error to …

feat: return errors from resource.New

---

README.md
RELEASING.md
go.mod
go.sum
otelconfig/otelconfig.go
otelconfig/otelconfig_test.go

- it's easy to mismatch semantic convention versions (see notes in #59 )
- Drop our version of semantic conventions to 1.17 to match those used in the imported otel-go package
- Update the README to clarify versions in use (note old semconv listed because that's in current available release)
- Update releasing notes to remember to adjust README if versions change, and some other cleanup for consistency to other repos
- Add simple unit test for checking semantic convention version against otel-go imported package semantic convention
- Add unit tests for resource detector from core (WithHost) and contrib (lambda) to confirm no schema error
Using a detector on the same version should work. These tests should fail if you change the semantic convention version back to 1.18.0 in the imports.

maint: Match semantic convention version to SDK semantic conventions

---

.github/release.yml

- auto-generated release notes are created without categories; a `release.yml` can be added to specify categorization based on labels (see [docs here](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) and usage in other repos).
- add `release.yml` with categorization based on other repos like [honeycomb-opentelemetry-go](https://github.com/honeycombio/honeycomb-opentelemetry-go/blob/main/.github/release.yml)
- also add `type: dependencies` label for maintenance category to avoid it being always dumped in Other Changes
next time we click auto-generate release notes we should see the changes in the appropriate categories based on label (or omitted entirely if set to `no-changelog`

maint: add release.yml for auto-generated release notes

---

.github/dependabot.yml

Adds dependency groups to dependabot config so related packages are updated together. 
- Add groups for otel and otel-contrib to dependabot config
Dependabot will group otel and otel contrib packages into PRs.

maint: Add dependency groups for otel and otel contrib packages

---

.github/dependabot.yml
README.md

- all otel dependencies should be updated together
- include both core and contrib otel deps in one dependabot group
- remove old line from readme that should've been deleted a while back
all core and contrib packages should be included in a single dependabot group PR

maint: combine otel core and contrib in dependabot groups 

---

otelconfig/pipelines/metrics.go
otelconfig/pipelines/trace.go

- Use predefined protocol constants instead of hard-coding the strings.

fix(pipelines): use protocol constants

---

otelconfig/pipelines/metrics.go

- Simple maintenance
Removes a duplicated block of code that set the metric exporter's `WithSecure` option.
As expected, this removed code doesn't change the current behavior of the library.

fix: remove duplicate secureOption assignment

---

.circleci/config.yml
Makefile

We upload test reports for smoke tests for friendlier error reporting and tracking flaky tests. This lets us do that for unit tests, too.
- Friendlier error reporting in CI.
- Test coverage for recently release Go 1.22.
- gotestsum is on Circle's current Go runners, so we can use it to produce xUnit XML test run reports to upload to Circle.
- New Go is out. Let's test against it.
A unit test build's "TESTS" tab at Circle will have data instead of reporting "0 test results uploaded".

maint: upload test results to CircleCI & add Go 1.22 to test matrix

---

CHANGELOG.md
otelconfig/version.go

Prepares next release of otel-config-go.
- Updates version to 1.14.0
- Adds changelog entry
Next release of otel-config-go can be tagged and published.

rel: Prepare v1.14.0 release

---

CHANGELOG.md
README.md
otelconfig/version.go

Prepares next release of otel-config-go.
- Updates version to 1.15.0
- Adds changelog entry
Next release of otel-config-go can be tagged and published.

rel: Prepare v1.15.0 release

---

otelconfig/otelconfig.go
otelconfig/otelconfig_test.go

- Closes #120 
- Set default true options to use a pointer to a bool to allow overriding in code
- Add unit tests to check for in-code setting of Metrics or Traces Disabled
- Use separate message to clarify if signal is disabled due to missing endpoint or enabled set to false
Set `WithMetricsEnabled(false)` and `WithLogLevel("debug")` and see `MetricsEnabled` set to false. Same should hold for Traces now as well.

fix: allow disabling of config options that default to true
